name: Run unit tests
on: push

env: 
  PGPASSWORD: password

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    #Defining the Postgres DB service we will need to run the unit tests
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
#       - name: Check out code
#         uses: actions/checkout@v2
#       - name: Install poetry
#         run: |
#             curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
#             source $HOME/.poetry/env
#             poetry install -vv
      - name: Set up postgres
        run: |
            psql -h 127.0.0.1:5432 -U postgres -c 'SELECT version();'
            psql -h 127.0.0.1:5432 -U postgres -c "create database fence_test_tmp"
