name: Run unit tests
on: push

env: 
  PGPASSWORD: postgres

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    #Defining the Postgres DB service we will need to run the unit tests
    services:
      postgres:
        image: postgres:9.6-bullseye
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Install poetry
        run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry install -vv
      - name: Set up postgres
        run: |
            psql -h localhost -U postgres -c 'SELECT version();'
            psql -h localhost -U postgres -c "create database fence_test_tmp"
      - name: Finish arranging for test
        run: |
            sudo rm -f /etc/boto.cfg
            mkdir -p tests/resources/keys
            cd tests/resources/keys
            openssl genrsa -out test_private_key.pem 2048
            openssl rsa -in test_private_key.pem -pubout -out test_public_key.pem
            openssl genrsa -out test_private_key_2.pem 2048
            openssl rsa -in test_private_key_2.pem -pubout -out test_public_key_2.pem
            cd -
      - name: Run test
        run: | 
          source $HOME/.poetry/env
          poetry run pytest -vv --cov=fence --cov-report xml tests
      - name: Clean up from test
        run: |
          python3 -m python-codacy-coverage -r coverage.xml
          COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls
