on:
  pull_request:
  issue_comment:
    types: [created, edited]

name: Wool

jobs:
  runWool:
    name: Run black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: uc-cdis/wool@master
      if: github.event.pull_request.head.repo.full_name == 'uc-cdis/cdis-manifest'
      env:
        GITHUB_TOKEN: ${{ secrets.PLANXCYBORG_GITHUB_TOKEN || 'ignore' }}
